str = "now i am learning Python programming from programming school"
print(str.endswith("programming"))
print(str.capitalize())
print(str)
str = str.capitalize()
print(str)
print(str.replace("a", "O"))
print(str.replace("python", "java"))
print(str.find("a"))
print(str.find("python"))
print(str.find("u"))
print(str.count("r"))
print(str.count("programming"))
print(str.lower())
print(str.upper())
print(str.title())