# TUPLE
tup = (1, 2, 3, 4, 5)
print(tup)
print(type(tup))
print(len(tup))
print(tup[0])
print(tup[-1])
print(tup[1:4])
print(tup + (6, 7, 8)) 
print(tup * 2)
print(3 in tup)
print(tup.count(2)) 
print(tup.index(4))
print(sorted(tup))
print(list(tup))
print(tuple([6, 7, 8]))
print(set(tup))
print(dict.fromkeys(tup, 'value'))
print(tup.__sizeof__())
print(dir(tup))
print(help(tup))